name: PHP CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Ganti dengan versi PHP yang Anda inginkan
    - name: Install Dependencies
      run: composer install # Jika Anda menggunakan Composer
    - name: Run PHP
      run: php index.php
